name: Testing CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  setup-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install coverage module
        run: sudo apt install python3-coverage

  test-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Coverage report
        run: python -m coverage report

      - name: Run tests
        run: python -m unittest

  setup-windows:
    runs-on: window-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install coverage module
        run: pip install coverage

  test-windows:
    runs-on: window-latest

    steps:
      - uses: actions/checkout@v4

      - name: Coverage report
        run: python -m coverage report

      - name: Run tests
        run: python -m unittest
